web-pal/chronos-timetracker

app/sagas/profile.js
=> fix(Authorization): use jira link with additional slug

app/containers/IssueView/IssueReport/IssueReport.jsx
=> fix(Issue Detail View): estimated and Remaining confused

app/containers/IssueView/IssueDetails/IssueDetails.jsx, app/containers/IssueView/IssueWorklogs/WorklogItem.jsx, app/containers/IssueView/IssueWorklogs/styled/index.jsx, app/containers/Modals/WorklogModal/EditWorklogModal.jsx, app/store/configureStore.development.js
=> fix(Issue Detail View): show edited worklogs

app/sagas/issues.js, app/store/configureStore.development.js
=> feat(Browsing Issues): remember issues filter

app/containers/IssueView/IssueReport/IssueReport.jsx
=> fix(Issue Detail View): total logged not updated after loading worklog

app/containers/Modals/WorklogModal/EditWorklogModal.jsx, app/containers/Modals/WorklogModal/WorklogModal.jsx
=> fix(Tracking): autofocus on worklog comment input

app/containers/IssueView/IssueWorklogs/IssueWorklogs.jsx, app/containers/IssueView/IssueWorklogs/WorklogItem.jsx, app/containers/IssueView/IssueWorklogs/styled/index.jsx, app/sagas/issues.js
=> fix(Issue Detail View): constantly highlight selected worklog from recent worklogs

app/containers/Sidebar/SidebarRecentItems/SidebarRecentItems.jsx, app/containers/Sidebar/SidebarRecentItems/WorklogItem/WorklogItem.jsx, app/containers/Sidebar/SidebarRecentItems/WorklogItem/styled/index.jsx
=> fix(Browsing Issues): show button on Recent worklogs

app/containers/Modals/WorklogModal/EditWorklogModal.jsx, app/containers/Modals/WorklogModal/WorklogModal.jsx
=> fix(Tracking): clear worklog comment after log work action

app/containers/IssueView/IssueWorklogs/IssueWorklogs.jsx
=> fix(Browsing Issues): sort descending worklogs by date

app/actions/ui.js, app/containers/Sidebar/IssuesSourcePicker/IssuesSourcePicker.jsx
reset search input when the project is changed
=> fix(Browsing Issues): fix search input

app/containers/Modals/WorklogModal/WorklogModal.jsx
=> feat: add adjust start time checkbox to worklog modal

app/containers/IssueView/TrackingBar/WorklogCommentDialog/WorklogCommentDialog.jsx, app/containers/IssueView/TrackingBar/WorklogCommentDialog/WorklogCommentOptions.jsx, app/containers/IssueView/TrackingBar/WorklogCommentDialog/styled/index.jsx, app/reducers/ui.js, app/sagas/worklogs.js, app/types/ui.js
=> feat(Tracking): add checkbox to post comment also as issue comment

app/containers/IssueView/IssueComments/styled/index.jsx
=> fix(Issue Detail View): fix too wide comments tab if comments too long

package.json
switch fetch method for scrum boards from "getIssuesForBoard" to "search"
ISSUES CLOSED: 94
=> fix(Browsing Issues): fix for filter of issues for sprint

app/containers/IssueView/IssueReport/MainColumn/ProgressBar/ProgressBar.jsx, app/containers/IssueView/IssueReport/MainColumn/ProgressBar/styled/index.jsx, app/containers/IssueView/TrackingBar/ProgressBar/CircularProgressBar.jsx, app/containers/IssueView/TrackingBar/ProgressBar/ProgressBar.jsx, app/containers/IssueView/TrackingBar/ProgressBar/styled/index.jsx, app/containers/IssueView/TrackingBar/TrackingBar.jsx, app/containers/IssueView/TrackingBar/styled/index.jsx, app/containers/Modals/SettingsModal/General/GeneralSettings.jsx, app/containers/Modals/SettingsModal/SettingsModal.jsx, app/sagas/filters.js, app/sagas/initializeApp.js, app/selectors/issues.js, app/types/issuesFields.js, app/types/issuesReports.js, app/utils/api/issues.js
=> feat(Tracking): display traking info progress bar

app/main/index.js, app/renderer/api/profile.js, app/renderer/containers/Popups/IssueForm/IssueForm.jsx, app/renderer/containers/Sidebar/SidebarIssues/IssuesHeader/IssuesHeader.jsx, app/renderer/sagas/auth.js
=> fix(Auth): sso crowd authentication

app/renderer/sagas/auth.js, app/renderer/sagas/boards.js, app/renderer/sagas/comments.js, app/renderer/sagas/filters.js, app/renderer/sagas/index.js, app/renderer/sagas/initialize.js, app/renderer/sagas/issues.js, app/renderer/sagas/projects.js, app/renderer/sagas/screenshots.js, app/renderer/sagas/settings.js, app/renderer/sagas/socket.js, app/renderer/sagas/sprints.js, app/renderer/sagas/timer.js, app/renderer/sagas/ui.js, app/renderer/sagas/worklogTypes.js, app/renderer/sagas/worklogs.js, app/shared/sagas/windowsManager.js
=> Refactor sagas

afterPack.js, app/renderer/sagas/screenshots.js, package.json
=> screenshots for windows

app/renderer/containers/IssueView/IssueDetails/IssueDetails.jsx, app/renderer/containers/IssueView/IssueDetails/styled/index.jsx
=> fix: fix issue label overflow
